# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ppreez <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/05/15 17:43:33 by ppreez            #+#    #+#              #
#    Updated: 2018/05/31 08:03:09 by rhohls           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

FILES = ft_lstdel.c			\ft_putchar.c		\ft_strdel.c		\ft_strnequ.c	\
		ft_lstdelone.c		\ft_putchar_fd.c	\ft_strdup.c		\ft_strnew.c	\
		ft_lstiter.c		\ft_putendl.c		\ft_strequ.c		\ft_strnstr.c	\
		ft_atoi.c			\ft_lstmap.c		\ft_putendl_fd.c	\ft_striter.c	\ft_strrchr.c 	\
		ft_bzero.c			\ft_lstnew.c		\ft_putnbr.c		\ft_striteri.c	\ft_strsplit.c	\
		ft_int_len.c		\ft_memalloc.c		\ft_putnbr_fd.c		\ft_strjoin.c	\ft_strstr.c	\
		ft_int_len_neg.c	\ft_memccpy.c		\ft_putstr.c		\ft_strlcat.c	\ft_strsub.c	\
		ft_isalnum.c		\ft_memchr.c		\ft_putstr_fd.c		\ft_strlen.c	\ft_strtrim.c	\
		ft_isalpha.c		\ft_memcmp.c		\ft_strcat.c		\ft_strmap.c	\ft_strvalid.c	\
		ft_isascii.c		\ft_memcpy.c		\ft_strchr.c		\ft_strmapi.c	\ft_tolower.c	\
		ft_isdigit.c		\ft_memdel.c		\ft_strclr.c		\ft_strncat.c	\ft_toupper.c	\
		ft_isprint.c		\ft_memmove.c		\ft_strcmp.c		\ft_strncmp.c	\ft_whitespace.c\
		ft_itoa.c			\ft_memset.c		\ft_strcmp_simple.c	\ft_strncmp_simple.c\
		ft_lstadd.c			\ft_power.c			\ft_strcpy.c		\ft_strncpy.c

OBJS = $(FILES:.c=.o) 

F?=test 

$(NAME): $(OBJ)
	gcc -c -Wall -Werror -Wextra $(FILES)
	ar -rcv $(NAME) $(OBJS)

all: $(NAME)

clean:
	/bin/rm -f $(OBJS)

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all

test: $(NAME)
	gcc ./test/test_$(F).c $(NAME)


.PHONY: re fclean clean all
